spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/gymdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: gymuser
    password: gympassword
  liquibase:
    change-log: "classpath:/liquibase/liquibase-changeLog.xml"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: validate